name: Docker Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -f frontend/Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest ./frontend
          docker build -f backend/Dockerfile.backend -t ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest


      - name: SSH into EC2 and pull latest Docker images
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest
            docker stop frontend-prod || true && docker rm frontend-prod || true
            docker stop backend-prod || true && docker rm backend-prod || true
            docker run -d --name frontend-prod -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/expense-frontend:latest
            docker run -d \
            --name backend-prod \
            --env-file /home/ubuntu/expense-tracker/.env \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/expense-backend:latest